### PR TITLE
Add initial repository content

### PR DESCRIPTION
**Pull request by cmichi**
The most important commit to review is "[Modify `node-template` for `substrate-contracts-node`](https://github.com/paritytech/substrate-contracts-node/commit/ccb1f86d8b1648bf6c075c8d31eac635de01b86b)".

Preview of the readme [can be found here](https://github.com/paritytech/substrate-contracts-node/tree/cmichi-add-initial-node).

As a follow-up I'll adapt our ink! tutorials, workshop and `ink-docs` to reference this node instead of the `canvas-node`. This is a pre-condition for merging https://github.com/paritytech/canvas-node/pull/73, as we would break existing tutorials, etc. otherwise.

We subsequently also need to adapt [`ink-waterfall`](https://github.com/paritytech/ink-waterfall) to use this node for testing. This can only be done after we have GitLab set-up for this repo though. I've created https://github.com/paritytech/ci_cd/issues/189 for 
this. After that is done we can add the `.gitlab-ci.yml` from `canvas-node`.

### CODE REVIEW

**Review by ascjones — APPROVED** [review]
LGTM

**Comment by athei** [comment]
Should we really include the `pallet_template` here? This isn't supposed to be a template.

**Comment by cmichi** [comment]
> Should we really include the `pallet_template` here? This isn't supposed to be a template.

I can take it out, my initial thinking was to keep it as simple as possible to later automate this synchronization with Substrate's `node-template`.

**Review by athei — APPROVED** [review]
> I can take it out, my initial thinking was to keep it as simple as possible to later automate this synchronization with Substrate's node-template.

I don't care that much. If it makes life easier for you just leave it in. Was just making sure that this isn't an oversight.

**Review by HCastano — APPROVED** [review]

**Comment by HCastano** [comment]
@cmichi We should enable squash merges by default in the repo (I can't since I'm not a repo owner/admin)

**Pull request merged**
