### PR TITLE
Sync with polkadot-v0.9.42 branch

### PR DESCRIPTION
**Pull request by SkymanOne**
This PR syncs with the [`polkadot-v0.9.42`](https://github.com/paritytech/substrate/tree/polkadot-v0.9.42) branch.

### CODE REVIEW

**Review by athei — APPROVED** [review]

**Comment by ascjones** [comment]
CI needs fixing

**Comment by athei** [comment]
It is the integrity_test which fails because our allowed code size is too big for the max call stack depth. We either disable the test or we need to make a change in pallet-contracts to make the memory limit configurable.

**Comment by SkymanOne** [comment]
I temporarily disabled `cargo test --release --all` step in CI

**Comment by agryaznov** [comment]
> It is the integrity_test which fails because our allowed code size is too big for the max call stack depth. We either disable the test or we need to make a change in pallet-contracts to make the memory limit configurable.

It is configurable since [substrate#13565](https://github.com/paritytech/substrate/pull/13565/files#diff-70e9723e9db62816e35f6f885b6770a8449c75a6c2733e9fa7a245fe52c4656cR315) is merged, via `T::Schedule::get().limits.runtime_memory`

**Comment by athei** [comment]
> > It is the integrity_test which fails because our allowed code size is too big for the max call stack depth. We either disable the test or we need to make a change in pallet-contracts to make the memory limit configurable.
> 
> It is configurable since [substrate#13565](https://github.com/paritytech/substrate/pull/13565/files#diff-70e9723e9db62816e35f6f885b6770a8449c75a6c2733e9fa7a245fe52c4656cR315) is merged, via `T::Schedule::get().limits.runtime_memory`

Nice. We can enable the test with the next release then.

**Pull request merged**
