### PR TITLE
Add Codespaces to the repository

### PR DESCRIPTION
**Pull request by hummusonrails**
As discussed with @kianenigma, @PierreBesson and others, this pull request brings the ability to spin up a Codespace instance inside this repository. The PR has two components:

- `devContainer.json`: The setup instructions to initialize the instance with
- `postCreateCommand.sh`: A custom shell script to install the necessary dependencies for Substrate and the contracts node template on the Codespace instance that is invoked immediately after the instance is created

Once this is merged, we can then include links for folks to create their own Codespace with the contracts node template using their own GitHub account similar to the way [Rustlings does do](https://github.com/rust-lang/rustlings#browser).

### CODE REVIEW

**Comment by athei** [comment]
CI fails because we need to sync against the latest substrate release I think.

**Comment by SkymanOne** [comment]
Yep. Please merge or rebase `master` for your branch

**Comment by hummusonrails** [comment]
Thanks both. I'll go ahead and do that early this coming week.

**Comment by hummusonrails** [comment]
@athei and @SkymanOne This is now ready for a review again. 🙏🏻

**Review by oleg-plakida — APPROVED** [review]

**Pull request merged**
